name: Scene
assets:
  - id: 14898293749905318833
    source: res:/meshes/cube/cube.gltf
  - id: 7476664350855877632
    source: res:/meshes/chess/pawn/pawn.gltf
  - id: 3107844384939351421
    source: res:/meshes/tree/tree.gltf
  - id: 1080424834659736061
    source: res:/meshes/sphere/sphere.gltf
  - id: 5134925074828327929
    source: res:/skyboxes/hdr/clouds.envmap.yaml
  - id: 12635219300201724838
    source: res:/meshes/helmet/helmet.gltf
nodes:
  - id: 8166675539894478826
    tag: Black Pawn 8
    transform:
      position: {x: 3.5, y: 0.100000001, z: 3}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 7476664350855877632
        submeshes:
          - index: 0
            material: 13508489748257261100
  - id: 16653460978901791619
    tag: White Pawn 8
    transform:
      position: {x: 3.5, y: 0.100000001, z: -3}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 7476664350855877632
        submeshes:
          - index: 0
            material: 6156677542587610415
  - id: 12207840314053737359
    tag: Black Pawn 7
    transform:
      position: {x: 2.5, y: 0.100000001, z: 3}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 7476664350855877632
        submeshes:
          - index: 0
            material: 13508489748257261100
  - id: 1897938858399066515
    tag: White Pawn 7
    transform:
      position: {x: 2.5, y: 0.100000001, z: -3}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 7476664350855877632
        submeshes:
          - index: 0
            material: 6156677542587610415
  - id: 6593286187683706159
    tag: Black Pawn 6
    transform:
      position: {x: 1.5, y: 0.100000001, z: 3}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 7476664350855877632
        submeshes:
          - index: 0
            material: 13508489748257261100
  - id: 6238755202836304040
    tag: White Pawn 6
    transform:
      position: {x: 1.5, y: 0.100000001, z: -3}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 7476664350855877632
        submeshes:
          - index: 0
            material: 6156677542587610415
  - id: 4721028371805553902
    tag: Black Pawn 5
    transform:
      position: {x: 0.5, y: 0.100000001, z: 3}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 7476664350855877632
        submeshes:
          - index: 0
            material: 13508489748257261100
  - id: 7798712646085859545
    tag: White Pawn 5
    transform:
      position: {x: 0.5, y: 0.100000001, z: -3}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 7476664350855877632
        submeshes:
          - index: 0
            material: 6156677542587610415
  - id: 1968111292778560718
    tag: Black Pawn 4
    transform:
      position: {x: -0.5, y: 0.100000001, z: 3}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 7476664350855877632
        submeshes:
          - index: 0
            material: 13508489748257261100
  - id: 12248593608249996765
    tag: White Pawn 4
    transform:
      position: {x: -0.5, y: 0.100000001, z: -3}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 7476664350855877632
        submeshes:
          - index: 0
            material: 6156677542587610415
  - id: 15845531262942741947
    tag: Black Pawn 3
    transform:
      position: {x: -1.5, y: 0.100000001, z: 3}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 7476664350855877632
        submeshes:
          - index: 0
            material: 13508489748257261100
  - id: 13222940964542845828
    tag: White Pawn 3
    transform:
      position: {x: -1.5, y: 0.100000001, z: -3}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 7476664350855877632
        submeshes:
          - index: 0
            material: 6156677542587610415
  - id: 251225631985310622
    tag: Black Pawn 2
    transform:
      position: {x: -2.5, y: 0.100000001, z: 3}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 7476664350855877632
        submeshes:
          - index: 0
            material: 13508489748257261100
  - id: 10563490467210105185
    tag: White Pawn 2
    transform:
      position: {x: -2.5, y: 0.100000001, z: -3}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 7476664350855877632
        submeshes:
          - index: 0
            material: 6156677542587610415
  - id: 3581972328862839911
    tag: Black Pawn 1
    transform:
      position: {x: -3.5, y: 0.100000001, z: 3}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 7476664350855877632
        submeshes:
          - index: 0
            material: 13508489748257261100
  - id: 13465568076233358048
    tag: White Pawn 1
    transform:
      position: {x: -3.5, y: 0.100000001, z: -3}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 7476664350855877632
        submeshes:
          - index: 0
            material: 6156677542587610415
  - id: 10026901558566562819
    tag: Tree
    transform:
      position: {x: 2, y: 0, z: 2}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 3107844384939351421
        submeshes:
          - index: 0
            material: 13320449381599949470
          - index: 1
            material: 5062057664545426986
  - id: 918208140446618666
    tag: Base
    transform:
      position: {x: 0, y: 0, z: 0}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 100, y: 0.200000003, z: 100}
    components:
      static_mesh:
        mesh: 14898293749905318833
        submeshes:
          - index: 0
            material: 11538598379617101358
  - id: 6013120641621740656
    tag: Blue
    transform:
      position: {x: -5, y: 5, z: -2.5}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 2, y: 2, z: 2}
    components:
      static_mesh:
        mesh: 14898293749905318833
        submeshes:
          - index: 0
            material: 13903118153070444710
  - id: 10984595687160664931
    tag: Green
    transform:
      position: {x: -5, y: 5, z: 2.5}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 2, y: 2, z: 2}
    components:
      static_mesh:
        mesh: 14898293749905318833
        submeshes:
          - index: 0
            material: 3743077102457873351
  - id: 13071734553046436763
    tag: Red
    transform:
      position: {x: -5, y: 5, z: 0}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 2, y: 2, z: 2}
    components:
      static_mesh:
        mesh: 14898293749905318833
        submeshes:
          - index: 0
            material: 15864794865203501563
  - id: 15847977451911967473
    tag: Helmet
    transform:
      position: {x: 0, y: 5, z: 0}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 12635219300201724838
        submeshes:
          - index: 0
            material: 8780219390817153026
  - id: 13957909535592302705
    tag: Sphere44
    parent: 3058042213033665513
    transform:
      position: {x: 12, y: 17, z: 0}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 1080424834659736061
        submeshes:
          - index: 0
            material: 383667568333031915
  - id: 1594344135374630055
    tag: Sphere34
    parent: 3058042213033665513
    transform:
      position: {x: 9, y: 17, z: 0}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 1080424834659736061
        submeshes:
          - index: 0
            material: 11368336054619494673
  - id: 8284960048407365697
    tag: Sphere24
    parent: 3058042213033665513
    transform:
      position: {x: 6, y: 17, z: 0}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 1080424834659736061
        submeshes:
          - index: 0
            material: 15078070332124167327
  - id: 4251757117144253082
    tag: Sphere14
    parent: 3058042213033665513
    transform:
      position: {x: 3, y: 17, z: 0}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 1080424834659736061
        submeshes:
          - index: 0
            material: 8018425990295823957
  - id: 1653244197077202419
    tag: Sphere04
    parent: 3058042213033665513
    transform:
      position: {x: 0, y: 17, z: 0}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 1080424834659736061
        submeshes:
          - index: 0
            material: 1700406257829171694
  - id: 8344139752641231710
    tag: Sphere43
    parent: 3058042213033665513
    transform:
      position: {x: 12, y: 14, z: 0}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 1080424834659736061
        submeshes:
          - index: 0
            material: 16221749164531219249
  - id: 1947518795451042869
    tag: Sphere33
    parent: 3058042213033665513
    transform:
      position: {x: 9, y: 14, z: 0}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 1080424834659736061
        submeshes:
          - index: 0
            material: 13542585498496866688
  - id: 13591323226727023950
    tag: Sphere23
    parent: 3058042213033665513
    transform:
      position: {x: 6, y: 14, z: 0}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 1080424834659736061
        submeshes:
          - index: 0
            material: 13232360280749148025
  - id: 13072781556872332434
    tag: Sphere13
    parent: 3058042213033665513
    transform:
      position: {x: 3, y: 14, z: 0}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 1080424834659736061
        submeshes:
          - index: 0
            material: 7526374794625559935
  - id: 4887264910522261349
    tag: Sphere03
    parent: 3058042213033665513
    transform:
      position: {x: 0, y: 14, z: 0}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 1080424834659736061
        submeshes:
          - index: 0
            material: 11771799700597375342
  - id: 3717240981145388256
    tag: Sphere42
    parent: 3058042213033665513
    transform:
      position: {x: 12, y: 11, z: 0}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 1080424834659736061
        submeshes:
          - index: 0
            material: 14423587531568392652
  - id: 6797292598049750399
    tag: Sphere32
    parent: 3058042213033665513
    transform:
      position: {x: 9, y: 11, z: 0}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 1080424834659736061
        submeshes:
          - index: 0
            material: 5013498393541931554
  - id: 3757598048825270128
    tag: Sphere22
    parent: 3058042213033665513
    transform:
      position: {x: 6, y: 11, z: 0}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 1080424834659736061
        submeshes:
          - index: 0
            material: 14479222056496126519
  - id: 13684671513134633561
    tag: Sphere12
    parent: 3058042213033665513
    transform:
      position: {x: 3, y: 11, z: 0}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 1080424834659736061
        submeshes:
          - index: 0
            material: 12327505273141194224
  - id: 638776187732371422
    tag: Sphere02
    parent: 3058042213033665513
    transform:
      position: {x: 0, y: 11, z: 0}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 1080424834659736061
        submeshes:
          - index: 0
            material: 10264129675033810589
  - id: 8792116536037520863
    tag: Sphere41
    parent: 3058042213033665513
    transform:
      position: {x: 12, y: 8, z: 0}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 1080424834659736061
        submeshes:
          - index: 0
            material: 16922530777795992881
  - id: 6402330086430767080
    tag: Sphere31
    parent: 3058042213033665513
    transform:
      position: {x: 9, y: 8, z: 0}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 1080424834659736061
        submeshes:
          - index: 0
            material: 8549742850815766792
  - id: 17557740821073535336
    tag: Sphere21
    parent: 3058042213033665513
    transform:
      position: {x: 6, y: 8, z: 0}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 1080424834659736061
        submeshes:
          - index: 0
            material: 17515895842764001405
  - id: 16263981337854315978
    tag: Sphere11
    parent: 3058042213033665513
    transform:
      position: {x: 3, y: 8, z: 0}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 1080424834659736061
        submeshes:
          - index: 0
            material: 11915918158191505442
  - id: 3891156959076177052
    tag: Sphere01
    parent: 3058042213033665513
    transform:
      position: {x: 0, y: 8, z: 0}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 1080424834659736061
        submeshes:
          - index: 0
            material: 1483409715740105541
  - id: 4096061904917322692
    tag: Sphere40
    parent: 3058042213033665513
    transform:
      position: {x: 12, y: 5, z: 0}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 1080424834659736061
        submeshes:
          - index: 0
            material: 9227602844055784050
  - id: 3744676801210606864
    tag: Sphere30
    parent: 3058042213033665513
    transform:
      position: {x: 9, y: 5, z: 0}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 1080424834659736061
        submeshes:
          - index: 0
            material: 16778756660181347347
  - id: 14004979768887824266
    tag: Sphere20
    parent: 3058042213033665513
    transform:
      position: {x: 6, y: 5, z: 0}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 1080424834659736061
        submeshes:
          - index: 0
            material: 16067690074691147374
  - id: 2898412353079481678
    tag: Sphere10
    parent: 3058042213033665513
    transform:
      position: {x: 3, y: 5, z: 0}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 1080424834659736061
        submeshes:
          - index: 0
            material: 9430677304202560831
  - id: 12177248668849500843
    tag: Sphere00
    parent: 3058042213033665513
    transform:
      position: {x: 0, y: 5, z: 0}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
    components:
      static_mesh:
        mesh: 1080424834659736061
        submeshes:
          - index: 0
            material: 3985805430533244347
  - id: 3058042213033665513
    tag: Spheres
    transform:
      position: {x: 0, y: 0, z: -15}
      rotation: {x: 0, y: 0, z: 0, w: 1}
      scale: {x: 1, y: 1, z: 1}
  - id: 15231144800923822509
    tag: Camera
    transform:
      position: {x: 8.19843197, y: 13.1984329, z: 8.19843197}
      rotation: {x: -0.218506277, y: 0.266794771, z: 0.0622431487, w: 0.936590314}
      scale: {x: 1, y: 1, z: 1}
    components:
      skybox:
        environment: 5134925074828327929
        tint: {r: 1, g: 1, b: 1, a: 1}