#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Jonas Kabelitz
#
# Regenerates libsbx/render/ui/fonts/*.hpp from their source .ttf files. Re-run whenever a source
# font is updated — the generated headers are checked in, not built.
#
# Usage (from the repo root): python ./scripts/generate_embedded_fonts.py

import os


def generate(input_path: str, array_name: str, output_path: str) -> None:
    with open(input_path, "rb") as f:
        data = f.read()

    guard = f"LIBSBX_RENDER_UI_FONTS_{array_name.upper()}_HPP_"
    source_name = os.path.basename(input_path)

    with open(output_path, "w") as out:
        out.write("// SPDX-License-Identifier: MIT\n")
        out.write("// Copyright (c) 2026 Jonas Kabelitz\n")
        out.write(f"// Generated by scripts/generate_embedded_fonts.py from {source_name} — do not edit by hand.\n")
        out.write(f"#ifndef {guard}\n#define {guard}\n\n")
        out.write("#include <cstddef>\n\n")
        out.write("namespace sbx::render::fonts {\n\n")
        out.write(f"inline constexpr unsigned char {array_name}[] = {{\n")

        line = []
        for byte in data:
            line.append(f"0x{byte:02x}")
            if len(line) == 20:
                out.write("  " + ",".join(line) + ",\n")
                line = []
        if line:
            out.write("  " + ",".join(line) + ",\n")

        out.write("};\n\n")
        out.write(f"inline constexpr std::size_t {array_name}_size = sizeof({array_name});\n\n")
        out.write("} // namespace sbx::render::fonts\n\n")
        out.write(f"#endif // {guard}\n")


def main() -> None:
    repo_root = os.path.abspath(os.getcwd())
    fonts_dir = os.path.join(repo_root, "libsbx", "render", "ui", "fonts", "generated")

    fonts = [
        (os.path.join(repo_root, "editor/assets/fonts/Roboto-Regular.ttf"), "roboto_regular_ttf"),
        (os.path.join(repo_root, "editor/assets/fonts/materialdesignicons-webfont.ttf"), "material_design_icons_ttf"),
    ]

    for input_path, array_name in fonts:
        output_path = os.path.join(fonts_dir, f"{array_name}.hpp")
        generate(input_path, array_name, output_path)
        print(f"Wrote {output_path} ({os.path.getsize(input_path)} bytes embedded)")


if __name__ == "__main__":
    main()
