// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Jonas Kabelitz
#include <libsbx/scripting/script_compiler.hpp>

#include <array>
#include <fstream>
#include <iterator>
#include <system_error>

#include <yaml-cpp/yaml.h>

#include <fmt/format.h>

#include <libsbx/utility/logger.hpp>
#include <libsbx/utility/hash.hpp>

#include <libsbx/core/engine.hpp>
#include <libsbx/core/project.hpp>

namespace sbx::scripting {

// Compiled format of script_compiler's own manifest schema — bumped whenever that schema (or
// what a recompile should be sensitive to) changes, forcing a one-time recompile on upgrade.
// Mirrors asset_cooker's per-cooker cooker_version, see this class's doc comment.
inline constexpr auto compiler_version = std::uint32_t{1u};

auto script_compiler::_write_ide_project(const std::filesystem::path& assets_directory, const std::filesystem::path& core_assembly_path) -> void {
  const auto path = assets_directory / "Game.csproj";

  auto absolute_core_assembly_path = core_assembly_path;
  auto ec = std::error_code{};
  const auto canonical = std::filesystem::weakly_canonical(core_assembly_path, ec);
  if (!ec) {
    absolute_core_assembly_path = canonical;
  }

  // TargetFramework must track Sbx.Core.csproj's own <TargetFramework> — bump both together.
  const auto content = fmt::format(
    "<!-- Auto-generated by libsbx (scripting::script_compiler) on every engine start — DO NOT EDIT.\n"
    "     Exists only so an IDE (VS Code/OmniSharp, Rider, Visual Studio) can resolve Sbx.Core for\n"
    "     autocomplete/IntelliSense. The engine never builds this project — these *.cs files are\n"
    "     compiled in-process via Roslyn (see script_compiler::compile_if_stale). -->\n"
    "<Project Sdk=\"Microsoft.NET.Sdk\">\n"
    "\n"
    "  <PropertyGroup>\n"
    "    <TargetFramework>net9.0</TargetFramework>\n"
    "    <ImplicitUsings>enable</ImplicitUsings>\n"
    "    <Nullable>enable</Nullable>\n"
    "    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>\n"
    "    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>\n"
    "    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>\n"
    "  </PropertyGroup>\n"
    "\n"
    "  <ItemGroup>\n"
    "    <Reference Include=\"Sbx.Core\">\n"
    "      <HintPath>{}</HintPath>\n"
    "      <Private>false</Private>\n"
    "    </Reference>\n"
    "  </ItemGroup>\n"
    "\n"
    "</Project>\n",
    absolute_core_assembly_path.generic_string()
  );

  if (std::filesystem::exists(path)) {
    auto existing = std::ifstream{path};
    const auto existing_content = std::string{std::istreambuf_iterator<char>{existing}, std::istreambuf_iterator<char>{}};

    if (existing_content == content) {
      return; // unchanged — don't touch mtime and trigger an IDE project reload for nothing
    }
  }

  std::filesystem::create_directories(path.parent_path());

  auto out = std::ofstream{path};
  out << content;
}

auto script_compiler::output_path() const -> std::filesystem::path {
  return core::engine::project().library_directory() / "scripts" / "Game.dll";
}

auto script_compiler::_manifest_path() const -> std::filesystem::path {
  return core::engine::project().library_directory() / "scripts" / "manifest.yaml";
}

auto script_compiler::_is_stale(const std::vector<std::filesystem::path>& sources, std::uint64_t core_assembly_hash) -> bool {
  if (!std::filesystem::exists(output_path())) {
    return true;
  }

  if (!_manifest_loaded) {
    const auto path = _manifest_path();

    if (std::filesystem::exists(path)) {
      try {
        const auto root = YAML::LoadFile(path.string());

        _manifest_compiler_version = root["compiler_version"].as<std::uint32_t>(0u);
        _manifest_core_assembly_hash = root["sbx_core_hash"].as<std::uint64_t>(0u);

        if (const auto sources_node = root["sources"]; sources_node) {
          for (const auto entry : sources_node) {
            auto source = source_entry{};
            source.hash = entry["hash"].as<std::uint64_t>(0u);
            source.mtime = entry["mtime"].as<std::int64_t>(0);

            _manifest_sources.emplace(entry["path"].as<std::string>(), source);
          }
        }
      } catch (const std::exception& exception) {
        utility::logger<"scripting">::warn("Could not read script manifest '{}' ({})", path.generic_string(), exception.what());
      }
    }

    _manifest_loaded = true;
  }

  if (_manifest_compiler_version != compiler_version || _manifest_core_assembly_hash != core_assembly_hash) {
    return true;
  }

  const auto& assets_directory = core::engine::project().assets_directory();

  if (sources.size() != _manifest_sources.size()) {
    return true;
  }

  for (const auto& source : sources) {
    const auto key = std::filesystem::relative(source, assets_directory).generic_string();

    const auto entry = _manifest_sources.find(key);

    if (entry == _manifest_sources.end()) {
      return true; // new file
    }

    auto error = std::error_code{};
    const auto mtime = std::filesystem::last_write_time(source, error);

    if (error) {
      return true;
    }

    const auto mtime_count = static_cast<std::int64_t>(mtime.time_since_epoch().count());

    if (entry->second.mtime == mtime_count) {
      continue; // fast path: unchanged since last compile
    }

    if (entry->second.hash != utility::hash_file(source)) {
      return true; // touched and actually changed
    }
  }

  return false;
}

auto script_compiler::_record_manifest(const std::vector<std::filesystem::path>& sources, std::uint64_t core_assembly_hash) -> void {
  const auto& assets_directory = core::engine::project().assets_directory();

  _manifest_compiler_version = compiler_version;
  _manifest_core_assembly_hash = core_assembly_hash;
  _manifest_sources.clear();

  auto root = YAML::Node{};
  root["compiler_version"] = compiler_version;
  root["sbx_core_hash"] = core_assembly_hash;

  auto sources_node = YAML::Node{YAML::NodeType::Sequence};

  for (const auto& source : sources) {
    const auto key = std::filesystem::relative(source, assets_directory).generic_string();

    auto error = std::error_code{};
    const auto mtime = std::filesystem::last_write_time(source, error);
    const auto mtime_count = error ? std::int64_t{0} : static_cast<std::int64_t>(mtime.time_since_epoch().count());
    const auto hash = utility::hash_file(source);

    _manifest_sources.emplace(key, source_entry{.hash = hash, .mtime = mtime_count});

    auto entry_node = YAML::Node{};
    entry_node["path"] = key;
    entry_node["hash"] = hash;
    entry_node["mtime"] = mtime_count;
    sources_node.push_back(entry_node);
  }

  root["sources"] = sources_node;

  const auto path = _manifest_path();
  std::filesystem::create_directories(path.parent_path());

  auto out = std::ofstream{path};
  out << root;
}

auto script_compiler::compile_if_stale(managed::runtime& runtime, const std::filesystem::path& core_assembly_path) -> void {
  auto& project = core::engine::project();

  // Independent of staleness below — an IDE needs this the moment a project has any scripts (or
  // even before), and regenerating it doesn't touch the compiled Game.dll/manifest at all.
  _write_ide_project(project.assets_directory(), core_assembly_path);

  auto sources = std::vector<std::filesystem::path>{};
  auto ec = std::error_code{};

  for (const auto& entry : std::filesystem::recursive_directory_iterator{project.assets_directory(), ec}) {
    if (!entry.is_regular_file()) {
      continue;
    }

    if (entry.path().extension() != ".cs") {
      continue;
    }

    sources.push_back(entry.path());
  }

  if (sources.empty()) {
    _last_compile_succeeded = true;
    return;
  }

  const auto core_assembly_hash = utility::hash_file(core_assembly_path);

  if (!_is_stale(sources, core_assembly_hash)) {
    _last_compile_succeeded = true; // manifest only ever records a successful compile
    return;
  }

  const auto final_path = output_path();
  std::filesystem::create_directories(final_path.parent_path());

  auto scratch_path = final_path;
  scratch_path += ".compiling";

  auto source_strings = std::vector<std::string>{};
  source_strings.reserve(sources.size());
  for (const auto& source : sources) {
    source_strings.push_back(source.string());
  }

  const auto reference_strings = std::vector<std::string>{core_assembly_path.string()};

  const auto result = runtime.compile_scripts(source_strings, reference_strings, scratch_path);

  for (const auto& diagnostic : result.diagnostics) {
    const auto location = diagnostic.file.empty() ? std::string{} : fmt::format("{}({},{}): ", diagnostic.file, diagnostic.line, diagnostic.column);

    if (diagnostic.is_error) {
      utility::logger<"scripting">::error("{}{}", location, diagnostic.message);
    } else {
      utility::logger<"scripting">::warn("{}{}", location, diagnostic.message);
    }
  }

  if (result.success) {
    // Atomic-ish replace: only ever overwrite the last-good assembly once a new one has fully
    // compiled — a failure below never touches final_path.
    std::filesystem::rename(scratch_path, final_path);

    _record_manifest(sources, core_assembly_hash);

    utility::logger<"scripting">::info("Compiled {} script(s) into '{}'", sources.size(), final_path.generic_string());

    _last_compile_succeeded = true;
  } else {
    std::filesystem::remove(scratch_path, ec);

    utility::logger<"scripting">::error("Script compilation failed — keeping the previous build (if any)");

    _last_compile_succeeded = false;
  }
}

} // namespace sbx::scripting
